services:
  postgres:
    build:
      context: ./postgres
    container_name: postgres_db
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres -c shared_preload_libraries=pg_cron
               -c cron.database_name=example_db

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_db
    restart: on-failure
    ports:
      - "8124:8123"
      - "9001:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: strongpassword
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: on-failure
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  pgdata:
  clickhouse_data:
  mongodb_data: